# Numpy Library

In [20]:
#import numpy Library

import numpy as np
from numpy import random

In [15]:
#create array

arr = np.array([[1,5,4,45],[54,47,4,5],[54,47,4,5]])
arr

array([[ 1,  5,  4, 45],
       [54, 47,  4,  5],
       [54, 47,  4,  5]])

In [16]:
arr.ndim #dimantion

2

In [17]:
arr.shape #shape of array

(3, 4)

In [18]:
type(arr)

numpy.ndarray

In [19]:
arr.data #memory location

# Random Number

In [37]:
x = random.randint(100)
x

89

In [39]:
x = random.rand(10)
x

array([0.22496512, 0.41732455, 0.30195909, 0.43537904, 0.55468844,
       0.9970743 , 0.49032681, 0.85447357, 0.78792527, 0.4232713 ])

In [42]:
x=random.randint(100)+random.rand(1)[0]
x

20.260636325825324

In [46]:
x = random.randint(10,size=(5,2))
x

array([[0, 5],
       [4, 3],
       [2, 7],
       [3, 5],
       [3, 8]])

In [58]:
#a = 1D Array , with 7 int
#b = 1D Array , with 7 int
#perform math opration

a = random.randint(100,size=(7))
print("a =",a)
b = random.randint(100,size=(7))
print("b =",b)

c = a+b
print("c =",c)

a = [ 3 45 46 33 41 85 32]
b = [45 58 49  0  5  8  0]
c = [ 48 103  95  33  46  93  32]


# Matrix 

In [73]:
a = np.matrix('1 2 12 ; 3 4 34 ; 5 6 45')
b = np.matrix([[1,5,4,45],[54,47,4,5],[54,47,4,5]])

In [74]:
print(b)

[[ 1  5  4 45]
 [54 47  4  5]
 [54 47  4  5]]


In [72]:
print(a)

[[ 1  2 12]
 [ 3  4 34]
 [ 5  6 45]]


# Central Tendency

In [76]:
c = np.array([[1,4,45],[54,4,5],[54,4,5]])

In [87]:
#minimum
print(np.amin(c))

#maximum
print(np.amax(c))

#mean
print(np.mean(c))

#median
print(np.median(c))

#standerd deviation
print(np.std(c))

#variance
print(np.var(c))

1
54
19.555555555555557
5.0
22.395987294905762
501.5802469135803
